us_state_number = {
    'Alabama': '1',
    'Alaska': '2',
    'American Samoa': '3',
    'Arizona': '4',
    'Arkansas': '5',
    'California': '6',
    'Colorado': '7',
    'Connecticut': '8',
    'Delaware': '9',
    'District of Columbia': '10',
    'Florida': '11',
    'Georgia': '12',
    'Guam': '13',
    'Hawaii': '14',
    'Idaho': '15',
    'Illinois': '16',
    'Indiana': '17',
    'Iowa': '18',
    'Kansas': '19',
    'Kentucky': '20',
    'Louisiana': '21',
    'Maine': '22',
    'Maryland': '23',
    'Massachusetts': '24',
    'Michigan': '25',
    'Minnesota': '26',
    'Mississippi': '27',
    'Missouri': '28',
    'Montana': '29',
    'Nebraska': '30',
    'Nevada': '31',
    'New Hampshire': '32',
    'New Jersey': '33',
    'New Mexico': '34',
    'New York': '35',
    'North Carolina': '36',
    'North Dakota': '37',
    'Northern Mariana Islands': '38',
    'Ohio': '39',
    'Oklahoma': '40',
    'Oregon': '41',
    'Pennsylvania': '42',
    'Puerto Rico': '43',
    'Rhode Island': '44',
    'South Carolina': '45',
    'South Dakota': '47',
    'Tennessee': '48',
    'Texas': '49',
    'Utah': '50',
    'Vermont': '51',
    'Virgin Islands': '52',
    'Virginia': '53',
    'Washington': '54',
    'West Virginia': '55',
    'Wisconsin': '56',
    'Wyoming': '57'
}

alphabet_handler = {'a':'1','b':'2','c':'3','d':'4','e':'5','f':'6','g':'7','h':'8','i':'9','j':'10','k':'11','l':'12','m':'13','n':'14','o':'15','p':'16','q':'17','r':'18','s':'19','t':'20','u':'21','v':'22','w':'23','x':'24','y':'25','z':'26'}